### ISSUE TITLE
SyntaxError on importing some packages when using register()

### ISSUE THREAD

**Issue by TheAsda** [nodejs/import-in-the-middle#107]
I'm using the [ts-rest](https://ts-rest.com) library. Without iitm it works just fine, but when i add iitm with `register` or `--loader` it throws `SyntaxError: The requested module '@ts-rest/core' does not provide an export named 'initContract'`.

## Steps to Reproduce the Problem
Here is the [reproduction repo](https://github.com/TheAsda/iitm-ts-rest-issue).
There are three scripts:
- start - regular launch with Node
- start:hook - launch with hook import
- start:register - launch with importing file with `register` call

## Specifications

Library version: 1.8.0
Node version: 20.11.1

**Comment by TheAsda** [comment]
If i remove "exports" section from ts-rest's package.json everything works fine

**Comment by TheAsda** [comment]
Looks like ts-rest has some weird bundling and "import" field in "exports" actually reexports cjs module as esm thus iitm fails to parse exported modules and proxies zero exports

**Comment by TheAsda** [comment]
I found a workaround:
```js
import { createRequire } from 'module';

const require = createRequire(import.meta.url);
const core = require('@ts-rest/core');
const { initContract } = core;
```

**Comment by TheAsda** [comment]
Looks like the issue comes from parsing exported modules. If you launch without iitm hook it loads cjs version of package then mjs. iitm parses wrong export and produces wrong virtual proxy file for the library

**Comment by TheAsda** [comment]
Looks like for some reason iitm treats package as cjs even though it has esm export

**Comment by timfish** [comment]
> for some reason iitm treats package as cjs even though it has esm export

Loader hooks (including iitm) load ESM and CJS loaded via ESM modules. 

iitm v1.8.1 has been released. Have you tried that yet?

**Comment by TheAsda** [comment]
Looks like the issue is actually with reexporting cjs as esm

<details>
<summary>Error</summary>

```
Error: 'import-in-the-middle' failed to wrap 'file:////ts-rest-iitm-issue/node_modules/@ts-rest/core/index.esm.js'
    at getSource (\ts-rest-iitm-issue\node_modules\import-in-the-middle\hook.js:304:21)
    at async load (\ts-rest-iitm-issue\node_modules\import-in-the-middle\hook.js:319:26)
    at async nextLoad (node:internal/modules/esm/hooks:865:22)
    at async Hooks.load (node:internal/modules/esm/hooks:448:20)
    at async MessagePort.handleMessage (node:internal/modules/esm/worker:196:18) {
  cause: Error: Unexpected export statement in CJS module.
    at @:462:8
      at esmSyntaxErr (\ts-rest-iitm-issue\node_modules\cjs-module-lexer\lexer.js:1153:24)
      at throwIfExportStatement (\ts-rest-iitm-issue\node_modules\cjs-module-lexer\lexer.js:1193:9)
      at parseSource (\ts-rest-iitm-issue\node_modules\cjs-module-lexer\lexer.js:155:13)
      at parseCJS (\ts-rest-iitm-issue\node_modules\cjs-module-lexer\lexer.js:43:5)
      at getCjsExports (\ts-rest-iitm-issue\node_modules\import-in-the-middle\lib\get-exports.js:37:20)
      at getExports (\ts-rest-iitm-issue\node_modules\import-in-the-middle\lib\get-exports.js:100:12)
      at async processModule (\ts-rest-iitm-issue\node_modules\import-in-the-middle\hook.js:131:23)
      at async getSource (\ts-rest-iitm-issue\node_modules\import-in-the-middle\hook.js:269:25)
      at async load (\ts-rest-iitm-issue\node_modules\import-in-the-middle\hook.js:319:26)
      at async nextLoad (node:internal/modules/esm/hooks:865:22) {
    code: 'ERR_LEXER_ESM_SYNTAX',
    loc: 15800
  }
}
node:internal/modules/esm/translators:116
  throw new ERR_INVALID_RETURN_PROPERTY_VALUE(
        ^

TypeError [ERR_INVALID_RETURN_PROPERTY_VALUE]: Expected string, array buffer, or typed array to be returned for the "source" from the "load" function but got undefined.       
    at assertBufferSource (node:internal/modules/esm/translators:116:9)
    at ModuleLoader.moduleStrategy (node:internal/modules/esm/translators:163:3)
    at callTranslator (node:internal/modules/esm/loader:285:14)
    at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:291:30) {
  code: 'ERR_INVALID_RETURN_PROPERTY_VALUE'
}
```
</details>

Here is the reproduction brand https://github.com/TheAsda/iitm-ts-rest-issue/tree/v1.8.1

**Comment by TheAsda** [comment]
The ".cjs.mjs" file reexports cjs module with export
![image](https://github.com/DataDog/import-in-the-middle/assets/35863331/bcb17ece-7204-4ec5-b85c-ed6764a85513)
![image](https://github.com/DataDog/import-in-the-middle/assets/35863331/f7bb4374-5779-45a5-9e6c-e20312942907)

**Comment by TheAsda** [comment]
If i replace "import" section with actual esm file different error occurs.

<details>
<summary>Error</summary>

```
Error: 'import-in-the-middle' failed to wrap 'file:////ts-rest-iitm-issue/node_modules/@ts-rest/core/index.esm.js'
    at getSource (\ts-rest-iitm-issue\node_modules\import-in-the-middle\hook.js:304:21)
    at async load (\ts-rest-iitm-issue\node_modules\import-in-the-middle\hook.js:319:26)
    at async nextLoad (node:internal/modules/esm/hooks:865:22)
    at async Hooks.load (node:internal/modules/esm/hooks:448:20)
    at async MessagePort.handleMessage (node:internal/modules/esm/worker:196:18) {
  cause: Error: Unexpected export statement in CJS module.
    at @:461:8
      at esmSyntaxErr (\ts-rest-iitm-issue\node_modules\cjs-module-lexer\lexer.js:1153:24)
      at throwIfExportStatement (\ts-rest-iitm-issue\node_modules\cjs-module-lexer\lexer.js:1193:9)
      at parseSource (\ts-rest-iitm-issue\node_modules\cjs-module-lexer\lexer.js:155:13)
      at parseCJS (\ts-rest-iitm-issue\node_modules\cjs-module-lexer\lexer.js:43:5)
      at getCjsExports (\ts-rest-iitm-issue\node_modules\import-in-the-middle\lib\get-exports.js:37:20)
      at getExports (\ts-rest-iitm-issue\node_modules\import-in-the-middle\lib\get-exports.js:100:12)
      at async processModule (\ts-rest-iitm-issue\node_modules\import-in-the-middle\hook.js:131:23)
      at async getSource (\ts-rest-iitm-issue\node_modules\import-in-the-middle\hook.js:269:25)
      at async load (\ts-rest-iitm-issue\node_modules\import-in-the-middle\hook.js:319:26)
      at async nextLoad (node:internal/modules/esm/hooks:865:22) {
    code: 'ERR_LEXER_ESM_SYNTAX',
    loc: 15778
  }
}
node:internal/modules/esm/translators:116
  throw new ERR_INVALID_RETURN_PROPERTY_VALUE(
        ^

TypeError [ERR_INVALID_RETURN_PROPERTY_VALUE]: Expected string, array buffer, or typed array to be returned for the "source" from the "load" function but got undefined.       
    at assertBufferSource (node:internal/modules/esm/translators:116:9)
    at ModuleLoader.moduleStrategy (node:internal/modules/esm/translators:163:3)
    at callTranslator (node:internal/modules/esm/loader:285:14)
    at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:291:30) {
  code: 'ERR_INVALID_RETURN_PROPERTY_VALUE'
}

Node.js v20.11.1
```

</details>

**Comment by TheAsda** [comment]
So the ".esm.js" file is an actual esm module that exports a bunch of properties
![image](https://github.com/DataDog/import-in-the-middle/assets/35863331/9a34dedc-fe27-4ddd-a1cd-f08a1ed7fb6e)
But it's being treated as cjs module for some reason

**Comment by TheAsda** [comment]
And the behavior when i remove "exports" from the package's package.json and app works fine persists

**Comment by TheAsda** [comment]
Currently i found a "fix" what temporarily fixes. I'm patching `@ts-rest/core` package with `yarn patch` and put cjs entrypoint to the "import".
![image](https://github.com/DataDog/import-in-the-middle/assets/35863331/a814addb-40e6-4ea3-8204-285967a59839)
It looks weird but works)

**Comment by TheAsda** [comment]
I just tried the latest iitm@1.11.0 with the latest @ts-rest/core@3.49.3 and it works now with all the cases. Here's the updated branch of [the repo](https://github.com/TheAsda/iitm-ts-rest-issue/tree/iitm%401.11.0).
