### ISSUE TITLE
Errors when importing vue/server-renderer

### ISSUE THREAD

**Issue by cjpearson** [nodejs/import-in-the-middle#139]
The `vue/server-renderer` export in the vue package re-exports `@vue/server-renderer`.  

## Expected Behavior

Applications which import `vue/server-renderer` will work fine when the `import-in-the-middle` hook is loaded.

## Actual Behavior

When attempting to open the application, the following error is logged:

```
[nuxt] [request error] [unhandled] [500] The requested module 'vue/server-renderer' does not provide an export named 'renderToString'
  at ModuleJob._instantiate (node:internal/modules/esm/module_job:131:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:213:5)
  at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
  at async Object.handler (./.output/server/chunks/runtime.mjs:2861:19)
  at async Server.toNodeHandle (./.output/server/chunks/runtime.mjs:3131:7)
[nuxt] [request error] [unhandled] [500] The requested module 'vue/server-renderer' does not provide an export named 'renderToString'
  at ModuleJob._instantiate (node:internal/modules/esm/module_job:131:21)
  at async ModuleJob.run (node:internal/modules/esm/module_job:213:5)
  at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
  at async Object.handler (./.output/server/chunks/runtime.mjs:2861:19)
  at async Server.toNodeHandle (./.output/server/chunks/runtime.mjs:3131:7)
```

## Steps to Reproduce the Problem

  1. Create a basic Nuxt app `npx nuxi init test-app`
  2. Add `import-in-the-middle` `yarn add import-in-the-middle`
  3. Build `yarn nuxt build`
  4. Run with `import-in-the-middle` `node --loader=import-in-the-middle/hook.mjs .output/server/index.mjs`

Alternatively, this single-file approach seems to recreate the problem

**index.mjs**
```
import { renderToString } from 'vue/server-renderer'

console.log('hello world')
```

```
❯ node index.mjs
hello world
❯ node --loader=import-in-the-middle/hook.mjs index.mjs
(node:75208) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("import-in-the-middle/hook.mjs", pathToFileURL("./"));'
(Use `node --trace-warnings ...` to show where the warning was created)
file:///private/tmp/import-test/index.mjs:1
import { renderToString } from 'vue/server-renderer'
         ^^^^^^^^^^^^^^
SyntaxError: The requested module 'vue/server-renderer' does not provide an export named 'renderToString'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:131:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:213:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:66:12)

Node.js v20.9.0
```

## Specifications

  - Version: 1.9.0 (Node v20.9.0)
  - Platform: MacOS
  - Subsystem:

**Comment by s1gr1d** [comment]
This was fixed with version `1.10.0` of `import-in-the-middle` 🎉 
ref: https://github.com/nodejs/import-in-the-middle/pull/140 and https://github.com/nodejs/import-in-the-middle/pull/145
